# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import calendar_pb2 as calendar__pb2
from . import common_pb2 as common__pb2


class CalendarServiceStub(object):
  """日历服务
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.list = channel.unary_unary(
        '/com.zhibeifw.proto.CalendarService/list',
        request_serializer=calendar__pb2.ProtoCalendarReq.SerializeToString,
        response_deserializer=calendar__pb2.ProtoCalendarListResp.FromString,
        )
    self.getGregorianRange = channel.unary_unary(
        '/com.zhibeifw.proto.CalendarService/getGregorianRange',
        request_serializer=common__pb2.ProtoEmpty.SerializeToString,
        response_deserializer=calendar__pb2.ProtoCalendarRangeResp.FromString,
        )


class CalendarServiceServicer(object):
  """日历服务
  """

  def list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getGregorianRange(self, request, context):
    """获得数据库中日历开始的起始和结束日期
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalendarServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'list': grpc.unary_unary_rpc_method_handler(
          servicer.list,
          request_deserializer=calendar__pb2.ProtoCalendarReq.FromString,
          response_serializer=calendar__pb2.ProtoCalendarListResp.SerializeToString,
      ),
      'getGregorianRange': grpc.unary_unary_rpc_method_handler(
          servicer.getGregorianRange,
          request_deserializer=common__pb2.ProtoEmpty.FromString,
          response_serializer=calendar__pb2.ProtoCalendarRangeResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.zhibeifw.proto.CalendarService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
