# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='com.zhibeifw.proto',
  syntax='proto3',
  serialized_options=_b('H\001\210\001\000'),
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x12\x63om.zhibeifw.proto\"\x0c\n\nProtoEmpty\"\x18\n\x0bProtoIntReq\x12\t\n\x01i\x18\x01 \x01(\x05\"\x1a\n\x0bProtoStrReq\x12\x0b\n\x03str\x18\x01 \x01(\t\"\x1f\n\x0fProtoIntListReq\x12\x0c\n\x04list\x18\x01 \x03(\x05\"\x1f\n\x0fProtoStrListReq\x12\x0c\n\x04list\x18\x01 \x03(\t\"0\n\x10ProtoGeneralResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\"7\n\x0cProtoIntResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\t\n\x01i\x18\x03 \x01(\x05\"9\n\x0cProtoStrResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x0b\n\x03str\x18\x03 \x01(\x05\">\n\x10ProtoStrListResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x0c\n\x04list\x18\x03 \x03(\t\">\n\x10ProtoIntListResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x0c\n\x04list\x18\x03 \x03(\x05\"O\n\x0fProtoUpsertResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x12\n\nupdateTime\x18\x04 \x01(\x03\"C\n\x16ProtoShareToWeixinResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\":\n\x0cProtoListReq\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0b\n\x03\x61sc\x18\x03 \x01(\x08\x42\x05H\x01\x88\x01\x00\x62\x06proto3')
)




_PROTOEMPTY = _descriptor.Descriptor(
  name='ProtoEmpty',
  full_name='com.zhibeifw.proto.ProtoEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=48,
)


_PROTOINTREQ = _descriptor.Descriptor(
  name='ProtoIntReq',
  full_name='com.zhibeifw.proto.ProtoIntReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='i', full_name='com.zhibeifw.proto.ProtoIntReq.i', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=74,
)


_PROTOSTRREQ = _descriptor.Descriptor(
  name='ProtoStrReq',
  full_name='com.zhibeifw.proto.ProtoStrReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='com.zhibeifw.proto.ProtoStrReq.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=102,
)


_PROTOINTLISTREQ = _descriptor.Descriptor(
  name='ProtoIntListReq',
  full_name='com.zhibeifw.proto.ProtoIntListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='com.zhibeifw.proto.ProtoIntListReq.list', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=135,
)


_PROTOSTRLISTREQ = _descriptor.Descriptor(
  name='ProtoStrListReq',
  full_name='com.zhibeifw.proto.ProtoStrListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='com.zhibeifw.proto.ProtoStrListReq.list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=168,
)


_PROTOGENERALRESP = _descriptor.Descriptor(
  name='ProtoGeneralResp',
  full_name='com.zhibeifw.proto.ProtoGeneralResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.zhibeifw.proto.ProtoGeneralResp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='com.zhibeifw.proto.ProtoGeneralResp.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=218,
)


_PROTOINTRESP = _descriptor.Descriptor(
  name='ProtoIntResp',
  full_name='com.zhibeifw.proto.ProtoIntResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.zhibeifw.proto.ProtoIntResp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='com.zhibeifw.proto.ProtoIntResp.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='com.zhibeifw.proto.ProtoIntResp.i', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=275,
)


_PROTOSTRRESP = _descriptor.Descriptor(
  name='ProtoStrResp',
  full_name='com.zhibeifw.proto.ProtoStrResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.zhibeifw.proto.ProtoStrResp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='com.zhibeifw.proto.ProtoStrResp.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str', full_name='com.zhibeifw.proto.ProtoStrResp.str', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=334,
)


_PROTOSTRLISTRESP = _descriptor.Descriptor(
  name='ProtoStrListResp',
  full_name='com.zhibeifw.proto.ProtoStrListResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.zhibeifw.proto.ProtoStrListResp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='com.zhibeifw.proto.ProtoStrListResp.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='com.zhibeifw.proto.ProtoStrListResp.list', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=398,
)


_PROTOINTLISTRESP = _descriptor.Descriptor(
  name='ProtoIntListResp',
  full_name='com.zhibeifw.proto.ProtoIntListResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.zhibeifw.proto.ProtoIntListResp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='com.zhibeifw.proto.ProtoIntListResp.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='com.zhibeifw.proto.ProtoIntListResp.list', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=462,
)


_PROTOUPSERTRESP = _descriptor.Descriptor(
  name='ProtoUpsertResp',
  full_name='com.zhibeifw.proto.ProtoUpsertResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.zhibeifw.proto.ProtoUpsertResp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='com.zhibeifw.proto.ProtoUpsertResp.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='com.zhibeifw.proto.ProtoUpsertResp.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updateTime', full_name='com.zhibeifw.proto.ProtoUpsertResp.updateTime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=543,
)


_PROTOSHARETOWEIXINRESP = _descriptor.Descriptor(
  name='ProtoShareToWeixinResp',
  full_name='com.zhibeifw.proto.ProtoShareToWeixinResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.zhibeifw.proto.ProtoShareToWeixinResp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='com.zhibeifw.proto.ProtoShareToWeixinResp.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='com.zhibeifw.proto.ProtoShareToWeixinResp.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=612,
)


_PROTOLISTREQ = _descriptor.Descriptor(
  name='ProtoListReq',
  full_name='com.zhibeifw.proto.ProtoListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='com.zhibeifw.proto.ProtoListReq.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='com.zhibeifw.proto.ProtoListReq.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asc', full_name='com.zhibeifw.proto.ProtoListReq.asc', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=672,
)

DESCRIPTOR.message_types_by_name['ProtoEmpty'] = _PROTOEMPTY
DESCRIPTOR.message_types_by_name['ProtoIntReq'] = _PROTOINTREQ
DESCRIPTOR.message_types_by_name['ProtoStrReq'] = _PROTOSTRREQ
DESCRIPTOR.message_types_by_name['ProtoIntListReq'] = _PROTOINTLISTREQ
DESCRIPTOR.message_types_by_name['ProtoStrListReq'] = _PROTOSTRLISTREQ
DESCRIPTOR.message_types_by_name['ProtoGeneralResp'] = _PROTOGENERALRESP
DESCRIPTOR.message_types_by_name['ProtoIntResp'] = _PROTOINTRESP
DESCRIPTOR.message_types_by_name['ProtoStrResp'] = _PROTOSTRRESP
DESCRIPTOR.message_types_by_name['ProtoStrListResp'] = _PROTOSTRLISTRESP
DESCRIPTOR.message_types_by_name['ProtoIntListResp'] = _PROTOINTLISTRESP
DESCRIPTOR.message_types_by_name['ProtoUpsertResp'] = _PROTOUPSERTRESP
DESCRIPTOR.message_types_by_name['ProtoShareToWeixinResp'] = _PROTOSHARETOWEIXINRESP
DESCRIPTOR.message_types_by_name['ProtoListReq'] = _PROTOLISTREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoEmpty = _reflection.GeneratedProtocolMessageType('ProtoEmpty', (_message.Message,), dict(
  DESCRIPTOR = _PROTOEMPTY,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoEmpty)
  ))
_sym_db.RegisterMessage(ProtoEmpty)

ProtoIntReq = _reflection.GeneratedProtocolMessageType('ProtoIntReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOINTREQ,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoIntReq)
  ))
_sym_db.RegisterMessage(ProtoIntReq)

ProtoStrReq = _reflection.GeneratedProtocolMessageType('ProtoStrReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSTRREQ,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoStrReq)
  ))
_sym_db.RegisterMessage(ProtoStrReq)

ProtoIntListReq = _reflection.GeneratedProtocolMessageType('ProtoIntListReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOINTLISTREQ,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoIntListReq)
  ))
_sym_db.RegisterMessage(ProtoIntListReq)

ProtoStrListReq = _reflection.GeneratedProtocolMessageType('ProtoStrListReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSTRLISTREQ,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoStrListReq)
  ))
_sym_db.RegisterMessage(ProtoStrListReq)

ProtoGeneralResp = _reflection.GeneratedProtocolMessageType('ProtoGeneralResp', (_message.Message,), dict(
  DESCRIPTOR = _PROTOGENERALRESP,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoGeneralResp)
  ))
_sym_db.RegisterMessage(ProtoGeneralResp)

ProtoIntResp = _reflection.GeneratedProtocolMessageType('ProtoIntResp', (_message.Message,), dict(
  DESCRIPTOR = _PROTOINTRESP,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoIntResp)
  ))
_sym_db.RegisterMessage(ProtoIntResp)

ProtoStrResp = _reflection.GeneratedProtocolMessageType('ProtoStrResp', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSTRRESP,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoStrResp)
  ))
_sym_db.RegisterMessage(ProtoStrResp)

ProtoStrListResp = _reflection.GeneratedProtocolMessageType('ProtoStrListResp', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSTRLISTRESP,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoStrListResp)
  ))
_sym_db.RegisterMessage(ProtoStrListResp)

ProtoIntListResp = _reflection.GeneratedProtocolMessageType('ProtoIntListResp', (_message.Message,), dict(
  DESCRIPTOR = _PROTOINTLISTRESP,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoIntListResp)
  ))
_sym_db.RegisterMessage(ProtoIntListResp)

ProtoUpsertResp = _reflection.GeneratedProtocolMessageType('ProtoUpsertResp', (_message.Message,), dict(
  DESCRIPTOR = _PROTOUPSERTRESP,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoUpsertResp)
  ))
_sym_db.RegisterMessage(ProtoUpsertResp)

ProtoShareToWeixinResp = _reflection.GeneratedProtocolMessageType('ProtoShareToWeixinResp', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSHARETOWEIXINRESP,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoShareToWeixinResp)
  ))
_sym_db.RegisterMessage(ProtoShareToWeixinResp)

ProtoListReq = _reflection.GeneratedProtocolMessageType('ProtoListReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOLISTREQ,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:com.zhibeifw.proto.ProtoListReq)
  ))
_sym_db.RegisterMessage(ProtoListReq)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
