# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tibetan_calendar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tibetan_calendar.proto',
  package='tibetan_calendar',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16tibetan_calendar.proto\x12\x10tibetan_calendar\"\x14\n\x04json\x12\x0c\n\x04text\x18\x01 \x01(\t2\x93\x01\n\x0fTibetanCalendar\x12\x41\n\rQueryCalendar\x12\x16.tibetan_calendar.json\x1a\x16.tibetan_calendar.json\"\x00\x12=\n\tUpdateDay\x12\x16.tibetan_calendar.json\x1a\x16.tibetan_calendar.json\"\x00\x62\x06proto3')
)




_JSON = _descriptor.Descriptor(
  name='json',
  full_name='tibetan_calendar.json',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='tibetan_calendar.json.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['json'] = _JSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

json = _reflection.GeneratedProtocolMessageType('json', (_message.Message,), dict(
  DESCRIPTOR = _JSON,
  __module__ = 'tibetan_calendar_pb2'
  # @@protoc_insertion_point(class_scope:tibetan_calendar.json)
  ))
_sym_db.RegisterMessage(json)



_TIBETANCALENDAR = _descriptor.ServiceDescriptor(
  name='TibetanCalendar',
  full_name='tibetan_calendar.TibetanCalendar',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=67,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryCalendar',
    full_name='tibetan_calendar.TibetanCalendar.QueryCalendar',
    index=0,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateDay',
    full_name='tibetan_calendar.TibetanCalendar.UpdateDay',
    index=1,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIBETANCALENDAR)

DESCRIPTOR.services_by_name['TibetanCalendar'] = _TIBETANCALENDAR

# @@protoc_insertion_point(module_scope)
