# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import tibetan_calendar_pb2 as tibetan__calendar__pb2


class TibetanCalendarStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.QueryCalendar = channel.unary_unary(
        '/tibetan_calendar.TibetanCalendar/QueryCalendar',
        request_serializer=tibetan__calendar__pb2.json.SerializeToString,
        response_deserializer=tibetan__calendar__pb2.json.FromString,
        )
    self.UpdateDay = channel.unary_unary(
        '/tibetan_calendar.TibetanCalendar/UpdateDay',
        request_serializer=tibetan__calendar__pb2.json.SerializeToString,
        response_deserializer=tibetan__calendar__pb2.json.FromString,
        )


class TibetanCalendarServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def QueryCalendar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateDay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TibetanCalendarServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'QueryCalendar': grpc.unary_unary_rpc_method_handler(
          servicer.QueryCalendar,
          request_deserializer=tibetan__calendar__pb2.json.FromString,
          response_serializer=tibetan__calendar__pb2.json.SerializeToString,
      ),
      'UpdateDay': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateDay,
          request_deserializer=tibetan__calendar__pb2.json.FromString,
          response_serializer=tibetan__calendar__pb2.json.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tibetan_calendar.TibetanCalendar', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
