# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: charge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='charge.proto',
  package='message_app',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63harge.proto\x12\x0bmessage_app\"\x14\n\x04json\x12\x0c\n\x04text\x18\x01 \x01(\t2\xe9\x02\n\rMessageCharge\x12;\n\x11QueryBusinessInfo\x12\x11.message_app.json\x1a\x11.message_app.json\"\x00\x12:\n\x10\x41\x64\x64MsgSendRecord\x12\x11.message_app.json\x1a\x11.message_app.json\"\x00\x12\x37\n\rGetChargeInfo\x12\x11.message_app.json\x1a\x11.message_app.json\"\x00\x12\x36\n\x0cUnifiedOrder\x12\x11.message_app.json\x1a\x11.message_app.json\"\x00\x12\x34\n\nCheckOrder\x12\x11.message_app.json\x1a\x11.message_app.json\"\x00\x12\x38\n\x0eQueryOrderList\x12\x11.message_app.json\x1a\x11.message_app.json\"\x00\x62\x06proto3')
)




_JSON = _descriptor.Descriptor(
  name='json',
  full_name='message_app.json',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='message_app.json.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['json'] = _JSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

json = _reflection.GeneratedProtocolMessageType('json', (_message.Message,), dict(
  DESCRIPTOR = _JSON,
  __module__ = 'charge_pb2'
  # @@protoc_insertion_point(class_scope:message_app.json)
  ))
_sym_db.RegisterMessage(json)



_MESSAGECHARGE = _descriptor.ServiceDescriptor(
  name='MessageCharge',
  full_name='message_app.MessageCharge',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=52,
  serialized_end=413,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryBusinessInfo',
    full_name='message_app.MessageCharge.QueryBusinessInfo',
    index=0,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddMsgSendRecord',
    full_name='message_app.MessageCharge.AddMsgSendRecord',
    index=1,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetChargeInfo',
    full_name='message_app.MessageCharge.GetChargeInfo',
    index=2,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UnifiedOrder',
    full_name='message_app.MessageCharge.UnifiedOrder',
    index=3,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckOrder',
    full_name='message_app.MessageCharge.CheckOrder',
    index=4,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryOrderList',
    full_name='message_app.MessageCharge.QueryOrderList',
    index=5,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGECHARGE)

DESCRIPTOR.services_by_name['MessageCharge'] = _MESSAGECHARGE

# @@protoc_insertion_point(module_scope)
