# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: live_collect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import live_longensi_pb2 as live__longensi__pb2

from .live_longensi_pb2 import *


DESCRIPTOR = _descriptor.FileDescriptor(
  name='live_collect.proto',
  package='live_app',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12live_collect.proto\x12\x08live_app\x1a\x13live_longensi.proto\"J\n\x11PlayBackColletReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x14\n\x0cplay_back_id\x18\x02 \x01(\x05\x12\x0e\n\x06method\x18\x03 \x01(\t\"Y\n\x11PlayBackColletRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x14\n\x0cplay_back_id\x18\x03 \x01(\x05\x12\x11\n\tcollected\x18\x04 \x01(\x05\x32\x9c\x01\n\x0fPlayBackCollect\x12\x45\n\x07\x43ollect\x12\x1b.live_app.PlayBackColletReq\x1a\x1b.live_app.PlayBackColletRsp\"\x00\x12\x42\n\x10GetCollectedList\x12\x15.live_app.PlayBackReq\x1a\x15.live_app.PlayBackRsp\"\x00P\x00\x62\x06proto3')
  ,
  dependencies=[live__longensi__pb2.DESCRIPTOR,],
  public_dependencies=[live__longensi__pb2.DESCRIPTOR,])




_PLAYBACKCOLLETREQ = _descriptor.Descriptor(
  name='PlayBackColletReq',
  full_name='live_app.PlayBackColletReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='live_app.PlayBackColletReq.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='play_back_id', full_name='live_app.PlayBackColletReq.play_back_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='live_app.PlayBackColletReq.method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=127,
)


_PLAYBACKCOLLETRSP = _descriptor.Descriptor(
  name='PlayBackColletRsp',
  full_name='live_app.PlayBackColletRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='live_app.PlayBackColletRsp.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='live_app.PlayBackColletRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='play_back_id', full_name='live_app.PlayBackColletRsp.play_back_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collected', full_name='live_app.PlayBackColletRsp.collected', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=218,
)

DESCRIPTOR.message_types_by_name['PlayBackColletReq'] = _PLAYBACKCOLLETREQ
DESCRIPTOR.message_types_by_name['PlayBackColletRsp'] = _PLAYBACKCOLLETRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayBackColletReq = _reflection.GeneratedProtocolMessageType('PlayBackColletReq', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBACKCOLLETREQ,
  __module__ = 'live_collect_pb2'
  # @@protoc_insertion_point(class_scope:live_app.PlayBackColletReq)
  ))
_sym_db.RegisterMessage(PlayBackColletReq)

PlayBackColletRsp = _reflection.GeneratedProtocolMessageType('PlayBackColletRsp', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBACKCOLLETRSP,
  __module__ = 'live_collect_pb2'
  # @@protoc_insertion_point(class_scope:live_app.PlayBackColletRsp)
  ))
_sym_db.RegisterMessage(PlayBackColletRsp)



_PLAYBACKCOLLECT = _descriptor.ServiceDescriptor(
  name='PlayBackCollect',
  full_name='live_app.PlayBackCollect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=221,
  serialized_end=377,
  methods=[
  _descriptor.MethodDescriptor(
    name='Collect',
    full_name='live_app.PlayBackCollect.Collect',
    index=0,
    containing_service=None,
    input_type=_PLAYBACKCOLLETREQ,
    output_type=_PLAYBACKCOLLETRSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCollectedList',
    full_name='live_app.PlayBackCollect.GetCollectedList',
    index=1,
    containing_service=None,
    input_type=live__longensi__pb2._PLAYBACKREQ,
    output_type=live__longensi__pb2._PLAYBACKRSP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYBACKCOLLECT)

DESCRIPTOR.services_by_name['PlayBackCollect'] = _PLAYBACKCOLLECT

# @@protoc_insertion_point(module_scope)
