# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import live_longensi_pb2 as live__longensi__pb2


class LiveFrontStub(object):
  """直播
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLatestLive = channel.unary_unary(
        '/live_app.LiveFront/GetLatestLive',
        request_serializer=live__longensi__pb2.LiveReq.SerializeToString,
        response_deserializer=live__longensi__pb2.LatestLiveRsp.FromString,
        )
    self.GetLiveStartTime = channel.unary_unary(
        '/live_app.LiveFront/GetLiveStartTime',
        request_serializer=live__longensi__pb2.LiveReq.SerializeToString,
        response_deserializer=live__longensi__pb2.LiveStartTimeRsp.FromString,
        )
    self.GetPlayBackList = channel.unary_unary(
        '/live_app.LiveFront/GetPlayBackList',
        request_serializer=live__longensi__pb2.PlayBackReq.SerializeToString,
        response_deserializer=live__longensi__pb2.PlayBackRsp.FromString,
        )
    self.AddPlayRecord = channel.unary_unary(
        '/live_app.LiveFront/AddPlayRecord',
        request_serializer=live__longensi__pb2.PlayRecordReq.SerializeToString,
        response_deserializer=live__longensi__pb2.CommonRsp.FromString,
        )
    self.GetSinglePlayBack = channel.unary_unary(
        '/live_app.LiveFront/GetSinglePlayBack',
        request_serializer=live__longensi__pb2.PlayRecordReq.SerializeToString,
        response_deserializer=live__longensi__pb2.SinglePlayBackRsp.FromString,
        )


class LiveFrontServicer(object):
  """直播
  """

  def GetLatestLive(self, request, context):
    """获取最近的直播
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLiveStartTime(self, request, context):
    """获取直播开始时间
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPlayBackList(self, request, context):
    """获取视频列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddPlayRecord(self, request, context):
    """添加播放记录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSinglePlayBack(self, request, context):
    """获取单条回放
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LiveFrontServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLatestLive': grpc.unary_unary_rpc_method_handler(
          servicer.GetLatestLive,
          request_deserializer=live__longensi__pb2.LiveReq.FromString,
          response_serializer=live__longensi__pb2.LatestLiveRsp.SerializeToString,
      ),
      'GetLiveStartTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetLiveStartTime,
          request_deserializer=live__longensi__pb2.LiveReq.FromString,
          response_serializer=live__longensi__pb2.LiveStartTimeRsp.SerializeToString,
      ),
      'GetPlayBackList': grpc.unary_unary_rpc_method_handler(
          servicer.GetPlayBackList,
          request_deserializer=live__longensi__pb2.PlayBackReq.FromString,
          response_serializer=live__longensi__pb2.PlayBackRsp.SerializeToString,
      ),
      'AddPlayRecord': grpc.unary_unary_rpc_method_handler(
          servicer.AddPlayRecord,
          request_deserializer=live__longensi__pb2.PlayRecordReq.FromString,
          response_serializer=live__longensi__pb2.CommonRsp.SerializeToString,
      ),
      'GetSinglePlayBack': grpc.unary_unary_rpc_method_handler(
          servicer.GetSinglePlayBack,
          request_deserializer=live__longensi__pb2.PlayRecordReq.FromString,
          response_serializer=live__longensi__pb2.SinglePlayBackRsp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'live_app.LiveFront', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
