# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: live.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='live.proto',
  package='live_app',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nlive.proto\x12\x08live_app\"\x14\n\x04json\x12\x0c\n\x04text\x18\x01 \x01(\t2\x81\x02\n\x0eLiveManagement\x12/\n\x0bGetLiveList\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12+\n\x07\x41\x64\x64Live\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12.\n\nUpdateLive\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12.\n\nDeleteLive\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12\x31\n\rGetLatestLive\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x32\x98\x02\n\x12PlayBackManagement\x12\x33\n\x0fGetPlayBackList\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12/\n\x0b\x41\x64\x64PlayBack\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12\x32\n\x0eUpdatePlayBack\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12\x32\n\x0e\x44\x65letePlayBack\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12\x34\n\x10GetNoAddPlayBack\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x32\xe9\x01\n\x14LiveStreamManagement\x12\x32\n\x0eGetLiveStreams\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12\x31\n\rAddLiveStream\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12\x34\n\x10UpdateLiveStream\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x12\x34\n\x10\x44\x65leteLiveStream\x12\x0e.live_app.json\x1a\x0e.live_app.json\"\x00\x62\x06proto3')
)




_JSON = _descriptor.Descriptor(
  name='json',
  full_name='live_app.json',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='live_app.json.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['json'] = _JSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

json = _reflection.GeneratedProtocolMessageType('json', (_message.Message,), dict(
  DESCRIPTOR = _JSON,
  __module__ = 'live_pb2'
  # @@protoc_insertion_point(class_scope:live_app.json)
  ))
_sym_db.RegisterMessage(json)



_LIVEMANAGEMENT = _descriptor.ServiceDescriptor(
  name='LiveManagement',
  full_name='live_app.LiveManagement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=47,
  serialized_end=304,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLiveList',
    full_name='live_app.LiveManagement.GetLiveList',
    index=0,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddLive',
    full_name='live_app.LiveManagement.AddLive',
    index=1,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateLive',
    full_name='live_app.LiveManagement.UpdateLive',
    index=2,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteLive',
    full_name='live_app.LiveManagement.DeleteLive',
    index=3,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatestLive',
    full_name='live_app.LiveManagement.GetLatestLive',
    index=4,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIVEMANAGEMENT)

DESCRIPTOR.services_by_name['LiveManagement'] = _LIVEMANAGEMENT


_PLAYBACKMANAGEMENT = _descriptor.ServiceDescriptor(
  name='PlayBackManagement',
  full_name='live_app.PlayBackManagement',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=307,
  serialized_end=587,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPlayBackList',
    full_name='live_app.PlayBackManagement.GetPlayBackList',
    index=0,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddPlayBack',
    full_name='live_app.PlayBackManagement.AddPlayBack',
    index=1,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdatePlayBack',
    full_name='live_app.PlayBackManagement.UpdatePlayBack',
    index=2,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeletePlayBack',
    full_name='live_app.PlayBackManagement.DeletePlayBack',
    index=3,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNoAddPlayBack',
    full_name='live_app.PlayBackManagement.GetNoAddPlayBack',
    index=4,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYBACKMANAGEMENT)

DESCRIPTOR.services_by_name['PlayBackManagement'] = _PLAYBACKMANAGEMENT


_LIVESTREAMMANAGEMENT = _descriptor.ServiceDescriptor(
  name='LiveStreamManagement',
  full_name='live_app.LiveStreamManagement',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=590,
  serialized_end=823,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLiveStreams',
    full_name='live_app.LiveStreamManagement.GetLiveStreams',
    index=0,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddLiveStream',
    full_name='live_app.LiveStreamManagement.AddLiveStream',
    index=1,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateLiveStream',
    full_name='live_app.LiveStreamManagement.UpdateLiveStream',
    index=2,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteLiveStream',
    full_name='live_app.LiveStreamManagement.DeleteLiveStream',
    index=3,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIVESTREAMMANAGEMENT)

DESCRIPTOR.services_by_name['LiveStreamManagement'] = _LIVESTREAMMANAGEMENT

# @@protoc_insertion_point(module_scope)
