# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import live_collect_pb2 as live__collect__pb2
from . import live_longensi_pb2 as live__longensi__pb2


class PlayBackCollectStub(object):
  """直播
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Collect = channel.unary_unary(
        '/live_app.PlayBackCollect/Collect',
        request_serializer=live__collect__pb2.PlayBackColletReq.SerializeToString,
        response_deserializer=live__collect__pb2.PlayBackColletRsp.FromString,
        )
    self.GetCollectedList = channel.unary_unary(
        '/live_app.PlayBackCollect/GetCollectedList',
        request_serializer=live__longensi__pb2.PlayBackReq.SerializeToString,
        response_deserializer=live__longensi__pb2.PlayBackRsp.FromString,
        )


class PlayBackCollectServicer(object):
  """直播
  """

  def Collect(self, request, context):
    """收藏添加/删除
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCollectedList(self, request, context):
    """获取收藏列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PlayBackCollectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Collect': grpc.unary_unary_rpc_method_handler(
          servicer.Collect,
          request_deserializer=live__collect__pb2.PlayBackColletReq.FromString,
          response_serializer=live__collect__pb2.PlayBackColletRsp.SerializeToString,
      ),
      'GetCollectedList': grpc.unary_unary_rpc_method_handler(
          servicer.GetCollectedList,
          request_deserializer=live__longensi__pb2.PlayBackReq.FromString,
          response_serializer=live__longensi__pb2.PlayBackRsp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'live_app.PlayBackCollect', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
