# Generated by Django 2.0.7 on 2019-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TibetanCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gregorian', models.CharField(max_length=20, verbose_name='公历')),
                ('chinese', models.CharField(max_length=20, verbose_name='农历')),
                ('tibetan', models.CharField(max_length=20, verbose_name='藏历')),
                ('holiday', models.CharField(max_length=200, verbose_name='节日')),
                ('img', models.CharField(max_length=200, verbose_name='日期主题图片')),
                ('year', models.IntegerField(default=2019, verbose_name='年')),
                ('month', models.IntegerField(default=1, verbose_name='月')),
            ],
            options={
                'verbose_name': '汉藏佛历',
                'verbose_name_plural': '汉藏佛历',
                'db_table': 'tibetan_calendar',
            },
        ),
    ]
