# Generated by Django 2.0.7 on 2019-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tibetan_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibetancalendar',
            name='mark',
            field=models.CharField(max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tibetancalendar',
            name='holiday',
            field=models.CharField(max_length=200, null=True, verbose_name='节日'),
        ),
        migrations.AlterField(
            model_name='tibetancalendar',
            name='img',
            field=models.CharField(max_length=200, null=True, verbose_name='日期主题图片'),
        ),
    ]
