# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buddha.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buddha.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\024com.jyzh.jetpet.grpc'),
  serialized_pb=_b('\n\x0c\x62uddha.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x06\x42uddha\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03pic\x18\x03 \x01(\t\"\xc1\x01\n\x10PrayBuddhaObject\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tbuddha_id\x18\x02 \x01(\x05\x12,\n\x08\x64\x61tetime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05light\x18\x04 \x01(\x08\x12\x0f\n\x07incense\x18\x05 \x01(\x08\x12\r\n\x05water\x18\x06 \x01(\x08\x12\x0e\n\x06\x66lower\x18\x07 \x01(\x08\x12\r\n\x05tower\x18\x08 \x01(\x08\x12\x12\n\nbuddha_pic\x18\t \x01(\tB\x16\n\x14\x63om.jyzh.jetpet.grpcb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_BUDDHA = _descriptor.Descriptor(
  name='Buddha',
  full_name='Buddha',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Buddha.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Buddha.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pic', full_name='Buddha.pic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=96,
)


_PRAYBUDDHAOBJECT = _descriptor.Descriptor(
  name='PrayBuddhaObject',
  full_name='PrayBuddhaObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PrayBuddhaObject.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buddha_id', full_name='PrayBuddhaObject.buddha_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='PrayBuddhaObject.datetime', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='light', full_name='PrayBuddhaObject.light', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='incense', full_name='PrayBuddhaObject.incense', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='water', full_name='PrayBuddhaObject.water', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flower', full_name='PrayBuddhaObject.flower', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tower', full_name='PrayBuddhaObject.tower', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buddha_pic', full_name='PrayBuddhaObject.buddha_pic', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=292,
)

_PRAYBUDDHAOBJECT.fields_by_name['datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Buddha'] = _BUDDHA
DESCRIPTOR.message_types_by_name['PrayBuddhaObject'] = _PRAYBUDDHAOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Buddha = _reflection.GeneratedProtocolMessageType('Buddha', (_message.Message,), dict(
  DESCRIPTOR = _BUDDHA,
  __module__ = 'buddha_pb2'
  # @@protoc_insertion_point(class_scope:Buddha)
  ))
_sym_db.RegisterMessage(Buddha)

PrayBuddhaObject = _reflection.GeneratedProtocolMessageType('PrayBuddhaObject', (_message.Message,), dict(
  DESCRIPTOR = _PRAYBUDDHAOBJECT,
  __module__ = 'buddha_pb2'
  # @@protoc_insertion_point(class_scope:PrayBuddhaObject)
  ))
_sym_db.RegisterMessage(PrayBuddhaObject)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
