# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import article_pb2 as article__pb2
import buddha_pb2 as buddha__pb2
import common_pb2 as common__pb2
import ebook_pb2 as ebook__pb2
import order_pb2 as order__pb2
import user_pb2 as user__pb2


class TempleServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Index = channel.unary_unary(
        '/TempleServer/Index',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.Search = channel.unary_unary(
        '/TempleServer/Search',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.GetHotKey = channel.unary_unary(
        '/TempleServer/GetHotKey',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.MetaDataSave = channel.unary_unary(
        '/TempleServer/MetaDataSave',
        request_serializer=article__pb2.MetaData.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.MetaDataDelete = channel.unary_unary(
        '/TempleServer/MetaDataDelete',
        request_serializer=article__pb2.MetaData.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.Register = channel.unary_unary(
        '/TempleServer/Register',
        request_serializer=user__pb2.User.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.Login = channel.unary_unary(
        '/TempleServer/Login',
        request_serializer=user__pb2.User.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.ChangePassword = channel.unary_unary(
        '/TempleServer/ChangePassword',
        request_serializer=user__pb2.User.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UserInfo = channel.unary_unary(
        '/TempleServer/UserInfo',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateUser = channel.unary_unary(
        '/TempleServer/UpdateUser',
        request_serializer=user__pb2.User.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetCode = channel.unary_unary(
        '/TempleServer/GetCode',
        request_serializer=user__pb2.CodeRequest.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UserBind = channel.unary_unary(
        '/TempleServer/UserBind',
        request_serializer=user__pb2.CodeRequest.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetUsers = channel.unary_unary(
        '/TempleServer/GetUsers',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.ManageUser = channel.unary_unary(
        '/TempleServer/ManageUser',
        request_serializer=user__pb2.UserDataOp.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetAddress = channel.unary_unary(
        '/TempleServer/GetAddress',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.CreateAddress = channel.unary_unary(
        '/TempleServer/CreateAddress',
        request_serializer=user__pb2.Address.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateAddress = channel.unary_unary(
        '/TempleServer/UpdateAddress',
        request_serializer=user__pb2.Address.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteAddress = channel.unary_unary(
        '/TempleServer/DeleteAddress',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetArticleList = channel.unary_unary(
        '/TempleServer/GetArticleList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.GetArticleDetail = channel.unary_unary(
        '/TempleServer/GetArticleDetail',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.CreateArticle = channel.unary_unary(
        '/TempleServer/CreateArticle',
        request_serializer=article__pb2.Article.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateArticle = channel.unary_unary(
        '/TempleServer/UpdateArticle',
        request_serializer=article__pb2.Article.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteArticle = channel.unary_unary(
        '/TempleServer/DeleteArticle',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetBannerList = channel.unary_unary(
        '/TempleServer/GetBannerList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.CreateBanner = channel.unary_unary(
        '/TempleServer/CreateBanner',
        request_serializer=article__pb2.Banner.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteBanner = channel.unary_unary(
        '/TempleServer/DeleteBanner',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetBuddha = channel.unary_unary(
        '/TempleServer/GetBuddha',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.CreateBuddha = channel.unary_unary(
        '/TempleServer/CreateBuddha',
        request_serializer=buddha__pb2.Buddha.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateBuddha = channel.unary_unary(
        '/TempleServer/UpdateBuddha',
        request_serializer=buddha__pb2.Buddha.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteBuddha = channel.unary_unary(
        '/TempleServer/DeleteBuddha',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetPrayBuddha = channel.unary_unary(
        '/TempleServer/GetPrayBuddha',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.CreateNewPray = channel.unary_unary(
        '/TempleServer/CreateNewPray',
        request_serializer=buddha__pb2.PrayBuddhaObject.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.PrayBuddha = channel.unary_unary(
        '/TempleServer/PrayBuddha',
        request_serializer=buddha__pb2.PrayBuddhaObject.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetGuruList = channel.unary_unary(
        '/TempleServer/GetGuruList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.GetGuruDetail = channel.unary_unary(
        '/TempleServer/GetGuruDetail',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.CreateGuru = channel.unary_unary(
        '/TempleServer/CreateGuru',
        request_serializer=ebook__pb2.Guru.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateGuru = channel.unary_unary(
        '/TempleServer/UpdateGuru',
        request_serializer=ebook__pb2.Guru.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteGuru = channel.unary_unary(
        '/TempleServer/DeleteGuru',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetEbookList = channel.unary_unary(
        '/TempleServer/GetEbookList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.GetEBook = channel.unary_unary(
        '/TempleServer/GetEBook',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.CreateEbook = channel.unary_unary(
        '/TempleServer/CreateEbook',
        request_serializer=ebook__pb2.EBook.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateEbook = channel.unary_unary(
        '/TempleServer/UpdateEbook',
        request_serializer=ebook__pb2.EBook.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteEbook = channel.unary_unary(
        '/TempleServer/DeleteEbook',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetQuestionList = channel.unary_unary(
        '/TempleServer/GetQuestionList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.CreateQuestion = channel.unary_unary(
        '/TempleServer/CreateQuestion',
        request_serializer=ebook__pb2.Questions.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.Replay = channel.unary_unary(
        '/TempleServer/Replay',
        request_serializer=ebook__pb2.Answer.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetQuestionDetail = channel.unary_unary(
        '/TempleServer/GetQuestionDetail',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteQuestion = channel.unary_unary(
        '/TempleServer/DeleteQuestion',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetCollectionsList = channel.unary_unary(
        '/TempleServer/GetCollectionsList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.Collection = channel.unary_unary(
        '/TempleServer/Collection',
        request_serializer=article__pb2.Collections.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.AlbumList = channel.unary_unary(
        '/TempleServer/AlbumList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.AlbumDetail = channel.unary_unary(
        '/TempleServer/AlbumDetail',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.CreateAlbum = channel.unary_unary(
        '/TempleServer/CreateAlbum',
        request_serializer=article__pb2.Album.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateAlbum = channel.unary_unary(
        '/TempleServer/UpdateAlbum',
        request_serializer=article__pb2.Album.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteAlbum = channel.unary_unary(
        '/TempleServer/DeleteAlbum',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.AddVoiceToAlbum = channel.unary_unary(
        '/TempleServer/AddVoiceToAlbum',
        request_serializer=article__pb2.AlbumVoice.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetVoice = channel.unary_unary(
        '/TempleServer/GetVoice',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.GetVoiceDetail = channel.unary_unary(
        '/TempleServer/GetVoiceDetail',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.CreateVoice = channel.unary_unary(
        '/TempleServer/CreateVoice',
        request_serializer=article__pb2.Voice.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateVoice = channel.unary_unary(
        '/TempleServer/UpdateVoice',
        request_serializer=article__pb2.Voice.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteVoice = channel.unary_unary(
        '/TempleServer/DeleteVoice',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetMaster = channel.unary_unary(
        '/TempleServer/GetMaster',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.CreateMaster = channel.unary_unary(
        '/TempleServer/CreateMaster',
        request_serializer=article__pb2.Master.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateMaster = channel.unary_unary(
        '/TempleServer/UpdateMaster',
        request_serializer=article__pb2.Master.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteMaster = channel.unary_unary(
        '/TempleServer/DeleteMaster',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.NoticeList = channel.unary_unary(
        '/TempleServer/NoticeList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.CreateNotice = channel.unary_unary(
        '/TempleServer/CreateNotice',
        request_serializer=article__pb2.Notice.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateNotice = channel.unary_unary(
        '/TempleServer/UpdateNotice',
        request_serializer=article__pb2.Notice.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteNotice = channel.unary_unary(
        '/TempleServer/DeleteNotice',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetDesc = channel.unary_unary(
        '/TempleServer/GetDesc',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.SaveDesc = channel.unary_unary(
        '/TempleServer/SaveDesc',
        request_serializer=common__pb2.Desc.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetColleges = channel.unary_unary(
        '/TempleServer/GetColleges',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.GetCollegeDetail = channel.unary_unary(
        '/TempleServer/GetCollegeDetail',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.CreateCollege = channel.unary_unary(
        '/TempleServer/CreateCollege',
        request_serializer=common__pb2.College.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateCollege = channel.unary_unary(
        '/TempleServer/UpdateCollege',
        request_serializer=common__pb2.College.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteCollege = channel.unary_unary(
        '/TempleServer/DeleteCollege',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetFlash = channel.unary_unary(
        '/TempleServer/GetFlash',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.CreateFlash = channel.unary_unary(
        '/TempleServer/CreateFlash',
        request_serializer=common__pb2.Flash.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.UpdateFlash = channel.unary_unary(
        '/TempleServer/UpdateFlash',
        request_serializer=common__pb2.Flash.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeleteFlash = channel.unary_unary(
        '/TempleServer/DeleteFlash',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetVipGoods = channel.unary_unary(
        '/TempleServer/GetVipGoods',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.DonateOnline = channel.unary_unary(
        '/TempleServer/DonateOnline',
        request_serializer=order__pb2.DonateReq.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DonateOffline = channel.unary_unary(
        '/TempleServer/DonateOffline',
        request_serializer=order__pb2.DonateOfflineReq.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.BuyVip = channel.unary_unary(
        '/TempleServer/BuyVip',
        request_serializer=order__pb2.ByVipReq.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetPayType = channel.unary_unary(
        '/TempleServer/GetPayType',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.getBankAccount = channel.unary_unary(
        '/TempleServer/getBankAccount',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.GetDonateOrderList = channel.unary_unary(
        '/TempleServer/GetDonateOrderList',
        request_serializer=common__pb2.Page.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )
    self.DeleteDonateOrder = channel.unary_unary(
        '/TempleServer/DeleteDonateOrder',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.ConfireDonateOrder = channel.unary_unary(
        '/TempleServer/ConfireDonateOrder',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.DeliverDonateGoods = channel.unary_unary(
        '/TempleServer/DeliverDonateGoods',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.SaveVipPrice = channel.unary_unary(
        '/TempleServer/SaveVipPrice',
        request_serializer=order__pb2.VipPrice.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetVipPrice = channel.unary_unary(
        '/TempleServer/GetVipPrice',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.Response.FromString,
        )
    self.GetVipRights = channel.unary_unary(
        '/TempleServer/GetVipRights',
        request_serializer=common__pb2.Temp.SerializeToString,
        response_deserializer=common__pb2.ListResponse.FromString,
        )


class TempleServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Index(self, request, context):
    """首页
    首页接口，返回Index
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    """search
    搜索接口 query 中参数为 search
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHotKey(self, request, context):
    """热搜获取
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MetaDataSave(self, request, context):
    """保存
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MetaDataDelete(self, request, context):
    """删除
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Register(self, request, context):
    """用户
    注册, 返回identity 放在 在msg中
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    """注册, 返回identity 放在 在msg中
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangePassword(self, request, context):
    """修改密码
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserInfo(self, request, context):
    """获取用户信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUser(self, request, context):
    """修改用户
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCode(self, request, context):
    """获取验证码
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserBind(self, request, context):
    """绑定邮箱，或手机号
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsers(self, request, context):
    """获取用户数据（admin）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ManageUser(self, request, context):
    """用户数据操作 (admin)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAddress(self, request, context):
    """收获地址
    获取收货地址
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAddress(self, request, context):
    """获取收货地址
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAddress(self, request, context):
    """获取收货地址
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAddress(self, request, context):
    """获取收货地址
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetArticleList(self, request, context):
    """文章
    获取文章列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetArticleDetail(self, request, context):
    """获取文章详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateArticle(self, request, context):
    """创建开示
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateArticle(self, request, context):
    """修改开示
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteArticle(self, request, context):
    """删除开示
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBannerList(self, request, context):
    """banner
    获取banaer 参数 改为PAGE， 需要传query值， {"location": "index"} 为首页，  {"location": "article"} 为开示页
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBanner(self, request, context):
    """创建banner
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBanner(self, request, context):
    """删除banner
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBuddha(self, request, context):
    """供佛
    获取佛像信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBuddha(self, request, context):
    """创建佛像
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateBuddha(self, request, context):
    """修改佛像
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBuddha(self, request, context):
    """删除佛像
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPrayBuddha(self, request, context):
    """获取供佛信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateNewPray(self, request, context):
    """添加供佛信息 （id 不用传）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PrayBuddha(self, request, context):
    """供佛 (Buddha 中信息都需要传)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGuruList(self, request, context):
    """上师（著作）
    获取上师列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGuruDetail(self, request, context):
    """获取上师详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateGuru(self, request, context):
    """创建上师
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGuru(self, request, context):
    """修改上师
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGuru(self, request, context):
    """删除上师
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEbookList(self, request, context):
    """电子书
    获取 电子书列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEBook(self, request, context):
    """	rpc AddBookToSheet (ID) returns (Response); // 将电子书添加到书架（开始阅读）
    电子书详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateEbook(self, request, context):
    """创建电子书
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateEbook(self, request, context):
    """创建电子书
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteEbook(self, request, context):
    """创建电子书
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetQuestionList(self, request, context):
    """问答
    获取问题列表 参数query {"location": "all"} 为问答列表（已回答）"my" 为我的问答
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateQuestion(self, request, context):
    """提交问题
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Replay(self, request, context):
    """回答
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetQuestionDetail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteQuestion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCollectionsList(self, request, context):
    """收藏
    获取收藏 query参数 type: ("1", "文章"), ("2", "电子书"), ("3", "视频"), ("4", "法音")
    参数 album_id 表示该专辑下的收藏法音
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Collection(self, request, context):
    """收藏/取消收藏
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AlbumList(self, request, context):
    """法音
    法音专辑列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AlbumDetail(self, request, context):
    """获取专辑中的法音列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAlbum(self, request, context):
    """创建专辑
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAlbum(self, request, context):
    """修改专辑
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAlbum(self, request, context):
    """删除专辑
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddVoiceToAlbum(self, request, context):
    """法音，专辑的绑定
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVoice(self, request, context):
    """获取法音列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVoiceDetail(self, request, context):
    """获取法音详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateVoice(self, request, context):
    """	rpc RemoveVoice (Voice) returns (Response); // 法音移除专辑
    创建法音
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateVoice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteVoice(self, request, context):
    """删除法音
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMaster(self, request, context):
    """获取法师
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateMaster(self, request, context):
    """添加法师
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateMaster(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteMaster(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NoticeList(self, request, context):
    """公告管理
    公告列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateNotice(self, request, context):
    """创建公告
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateNotice(self, request, context):
    """创建公告
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteNotice(self, request, context):
    """删除
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDesc(self, request, context):
    """龙恩寺简介
    获取龙恩寺简介
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveDesc(self, request, context):
    """保存龙恩寺简介
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetColleges(self, request, context):
    """获取学院列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCollegeDetail(self, request, context):
    """获取学院详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateCollege(self, request, context):
    """创建学院
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateCollege(self, request, context):
    """更新学院
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteCollege(self, request, context):
    """删除学院
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFlash(self, request, context):
    """获取闪屏
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateFlash(self, request, context):
    """创建闪屏
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateFlash(self, request, context):
    """更新闪屏
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteFlash(self, request, context):
    """删除闪屏
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVipGoods(self, request, context):
    """订单（乐捐，成为会员）
    获取会员购买价格
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DonateOnline(self, request, context):
    """乐捐线上订单
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DonateOffline(self, request, context):
    """乐捐线下订单
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuyVip(self, request, context):
    """成为会员
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPayType(self, request, context):
    """获取支付方式
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getBankAccount(self, request, context):
    """获取汇入账户
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDonateOrderList(self, request, context):
    """获取订单，参数query
    type ("1", "线上订单"), ("2", "线下订单"), ("3", "赠礼订单")
    create_time, 筛选日期
    username, 账号昵称筛选
    （admin）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteDonateOrder(self, request, context):
    """删除订单（admin）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfireDonateOrder(self, request, context):
    """审核订单（admin）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeliverDonateGoods(self, request, context):
    """确认发货（admin）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveVipPrice(self, request, context):
    """会员设置
    保存会员费用等设置（admin）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVipPrice(self, request, context):
    """获取（admin）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVipRights(self, request, context):
    """会员特权
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TempleServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Index': grpc.unary_unary_rpc_method_handler(
          servicer.Index,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'GetHotKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetHotKey,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'MetaDataSave': grpc.unary_unary_rpc_method_handler(
          servicer.MetaDataSave,
          request_deserializer=article__pb2.MetaData.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'MetaDataDelete': grpc.unary_unary_rpc_method_handler(
          servicer.MetaDataDelete,
          request_deserializer=article__pb2.MetaData.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=user__pb2.User.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=user__pb2.User.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'ChangePassword': grpc.unary_unary_rpc_method_handler(
          servicer.ChangePassword,
          request_deserializer=user__pb2.User.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.UserInfo,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUser,
          request_deserializer=user__pb2.User.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetCode': grpc.unary_unary_rpc_method_handler(
          servicer.GetCode,
          request_deserializer=user__pb2.CodeRequest.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UserBind': grpc.unary_unary_rpc_method_handler(
          servicer.UserBind,
          request_deserializer=user__pb2.CodeRequest.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetUsers': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsers,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'ManageUser': grpc.unary_unary_rpc_method_handler(
          servicer.ManageUser,
          request_deserializer=user__pb2.UserDataOp.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GetAddress,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'CreateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAddress,
          request_deserializer=user__pb2.Address.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAddress,
          request_deserializer=user__pb2.Address.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteAddress': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAddress,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetArticleList': grpc.unary_unary_rpc_method_handler(
          servicer.GetArticleList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'GetArticleDetail': grpc.unary_unary_rpc_method_handler(
          servicer.GetArticleDetail,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'CreateArticle': grpc.unary_unary_rpc_method_handler(
          servicer.CreateArticle,
          request_deserializer=article__pb2.Article.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateArticle': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateArticle,
          request_deserializer=article__pb2.Article.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteArticle': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteArticle,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetBannerList': grpc.unary_unary_rpc_method_handler(
          servicer.GetBannerList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'CreateBanner': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBanner,
          request_deserializer=article__pb2.Banner.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteBanner': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBanner,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetBuddha': grpc.unary_unary_rpc_method_handler(
          servicer.GetBuddha,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'CreateBuddha': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBuddha,
          request_deserializer=buddha__pb2.Buddha.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateBuddha': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateBuddha,
          request_deserializer=buddha__pb2.Buddha.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteBuddha': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBuddha,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetPrayBuddha': grpc.unary_unary_rpc_method_handler(
          servicer.GetPrayBuddha,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'CreateNewPray': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNewPray,
          request_deserializer=buddha__pb2.PrayBuddhaObject.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'PrayBuddha': grpc.unary_unary_rpc_method_handler(
          servicer.PrayBuddha,
          request_deserializer=buddha__pb2.PrayBuddhaObject.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetGuruList': grpc.unary_unary_rpc_method_handler(
          servicer.GetGuruList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'GetGuruDetail': grpc.unary_unary_rpc_method_handler(
          servicer.GetGuruDetail,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'CreateGuru': grpc.unary_unary_rpc_method_handler(
          servicer.CreateGuru,
          request_deserializer=ebook__pb2.Guru.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateGuru': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGuru,
          request_deserializer=ebook__pb2.Guru.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteGuru': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGuru,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetEbookList': grpc.unary_unary_rpc_method_handler(
          servicer.GetEbookList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'GetEBook': grpc.unary_unary_rpc_method_handler(
          servicer.GetEBook,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'CreateEbook': grpc.unary_unary_rpc_method_handler(
          servicer.CreateEbook,
          request_deserializer=ebook__pb2.EBook.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateEbook': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateEbook,
          request_deserializer=ebook__pb2.EBook.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteEbook': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteEbook,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetQuestionList': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuestionList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'CreateQuestion': grpc.unary_unary_rpc_method_handler(
          servicer.CreateQuestion,
          request_deserializer=ebook__pb2.Questions.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'Replay': grpc.unary_unary_rpc_method_handler(
          servicer.Replay,
          request_deserializer=ebook__pb2.Answer.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetQuestionDetail': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuestionDetail,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteQuestion': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteQuestion,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetCollectionsList': grpc.unary_unary_rpc_method_handler(
          servicer.GetCollectionsList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'Collection': grpc.unary_unary_rpc_method_handler(
          servicer.Collection,
          request_deserializer=article__pb2.Collections.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'AlbumList': grpc.unary_unary_rpc_method_handler(
          servicer.AlbumList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'AlbumDetail': grpc.unary_unary_rpc_method_handler(
          servicer.AlbumDetail,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'CreateAlbum': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAlbum,
          request_deserializer=article__pb2.Album.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateAlbum': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAlbum,
          request_deserializer=article__pb2.Album.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteAlbum': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAlbum,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'AddVoiceToAlbum': grpc.unary_unary_rpc_method_handler(
          servicer.AddVoiceToAlbum,
          request_deserializer=article__pb2.AlbumVoice.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetVoice': grpc.unary_unary_rpc_method_handler(
          servicer.GetVoice,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'GetVoiceDetail': grpc.unary_unary_rpc_method_handler(
          servicer.GetVoiceDetail,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'CreateVoice': grpc.unary_unary_rpc_method_handler(
          servicer.CreateVoice,
          request_deserializer=article__pb2.Voice.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateVoice': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateVoice,
          request_deserializer=article__pb2.Voice.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteVoice': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteVoice,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetMaster': grpc.unary_unary_rpc_method_handler(
          servicer.GetMaster,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'CreateMaster': grpc.unary_unary_rpc_method_handler(
          servicer.CreateMaster,
          request_deserializer=article__pb2.Master.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateMaster': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateMaster,
          request_deserializer=article__pb2.Master.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteMaster': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteMaster,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'NoticeList': grpc.unary_unary_rpc_method_handler(
          servicer.NoticeList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'CreateNotice': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNotice,
          request_deserializer=article__pb2.Notice.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateNotice': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateNotice,
          request_deserializer=article__pb2.Notice.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteNotice': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteNotice,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetDesc': grpc.unary_unary_rpc_method_handler(
          servicer.GetDesc,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'SaveDesc': grpc.unary_unary_rpc_method_handler(
          servicer.SaveDesc,
          request_deserializer=common__pb2.Desc.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetColleges': grpc.unary_unary_rpc_method_handler(
          servicer.GetColleges,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'GetCollegeDetail': grpc.unary_unary_rpc_method_handler(
          servicer.GetCollegeDetail,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'CreateCollege': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCollege,
          request_deserializer=common__pb2.College.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateCollege': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateCollege,
          request_deserializer=common__pb2.College.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteCollege': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteCollege,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetFlash': grpc.unary_unary_rpc_method_handler(
          servicer.GetFlash,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'CreateFlash': grpc.unary_unary_rpc_method_handler(
          servicer.CreateFlash,
          request_deserializer=common__pb2.Flash.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'UpdateFlash': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateFlash,
          request_deserializer=common__pb2.Flash.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeleteFlash': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteFlash,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetVipGoods': grpc.unary_unary_rpc_method_handler(
          servicer.GetVipGoods,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'DonateOnline': grpc.unary_unary_rpc_method_handler(
          servicer.DonateOnline,
          request_deserializer=order__pb2.DonateReq.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DonateOffline': grpc.unary_unary_rpc_method_handler(
          servicer.DonateOffline,
          request_deserializer=order__pb2.DonateOfflineReq.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'BuyVip': grpc.unary_unary_rpc_method_handler(
          servicer.BuyVip,
          request_deserializer=order__pb2.ByVipReq.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetPayType': grpc.unary_unary_rpc_method_handler(
          servicer.GetPayType,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'getBankAccount': grpc.unary_unary_rpc_method_handler(
          servicer.getBankAccount,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'GetDonateOrderList': grpc.unary_unary_rpc_method_handler(
          servicer.GetDonateOrderList,
          request_deserializer=common__pb2.Page.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
      'DeleteDonateOrder': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteDonateOrder,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'ConfireDonateOrder': grpc.unary_unary_rpc_method_handler(
          servicer.ConfireDonateOrder,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'DeliverDonateGoods': grpc.unary_unary_rpc_method_handler(
          servicer.DeliverDonateGoods,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'SaveVipPrice': grpc.unary_unary_rpc_method_handler(
          servicer.SaveVipPrice,
          request_deserializer=order__pb2.VipPrice.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetVipPrice': grpc.unary_unary_rpc_method_handler(
          servicer.GetVipPrice,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.Response.SerializeToString,
      ),
      'GetVipRights': grpc.unary_unary_rpc_method_handler(
          servicer.GetVipRights,
          request_deserializer=common__pb2.Temp.FromString,
          response_serializer=common__pb2.ListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TempleServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
