# Generated by Django 2.0.7 on 2019-07-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('msg_num', models.IntegerField(default=0, verbose_name='短信余量')),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
                'db_table': 'msg_business',
            },
        ),
        migrations.CreateModel(
            name='ChargePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='标题')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('charge_num', models.IntegerField(default=0, verbose_name='充值条数')),
            ],
            options={
                'verbose_name': '充值套餐',
                'verbose_name_plural': '充值套餐',
                'db_table': 'msg_charge_package',
            },
        ),
        migrations.CreateModel(
            name='MsgRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('state', models.IntegerField(default=1, verbose_name='状态')),
                ('business', models.ForeignKey(on_delete=None, to='message_app.Business', verbose_name='商户')),
            ],
            options={
                'verbose_name': '短信记录',
                'verbose_name_plural': '短信记录',
                'db_table': 'msg_record',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, verbose_name='订单号')),
                ('charge_num', models.IntegerField(default=0, verbose_name='充值条数')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('pay_type', models.IntegerField(default=1, verbose_name='支付方式')),
                ('state', models.IntegerField(default=1, verbose_name='状态')),
                ('business', models.ForeignKey(on_delete=None, to='message_app.Business', verbose_name='商户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'msg_order',
            },
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.IntegerField(default=1, verbose_name='支付方式')),
                ('app_id', models.CharField(max_length=50)),
                ('business', models.ForeignKey(on_delete=None, to='message_app.Business', verbose_name='商户')),
            ],
            options={
                'verbose_name': '支付信息',
                'verbose_name_plural': '支付信息',
                'db_table': 'msg_pay_info',
            },
        ),
    ]
