# Generated by Django 2.0.7 on 2019-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
