# Generated by Django 2.0.7 on 2019-07-16 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_auto_20190712_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='充值时间'),
            preserve_default=False,
        ),
    ]
