# Generated by Django 2.0.7 on 2019-06-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixinpay',
            name='cert',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证书'),
        ),
        migrations.AlterField(
            model_name='weixinpay',
            name='cert_key',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证书key'),
        ),
        migrations.AlterField(
            model_name='weixinpay',
            name='notify_url',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='回调链接'),
        ),
    ]
