# Generated by Django 2.0.7 on 2019-06-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0003_auto_20190619_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixinpay',
            name='mch_key',
            field=models.CharField(max_length=50),
        ),
    ]
