# Generated by Django 2.0.7 on 2019-06-20 03:08

from django.db import migrations, models
import pay_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0004_auto_20190619_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixinpay',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to=pay_app.models.cert_path, verbose_name='证书'),
        ),
        migrations.AlterField(
            model_name='weixinpay',
            name='cert_key',
            field=models.FileField(blank=True, null=True, upload_to=pay_app.models.key_path, verbose_name='证书key'),
        ),
    ]
