# Generated by Django 2.0.7 on 2019-07-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0006_alipay'),
    ]

    operations = [
#        migrations.AlterModelOptions(
#            name='alipay',
#            options={'verbose_name': '支付宝支付', 'verbose_name_plural': '支付宝支付'},
#        ),
#        migrations.AlterModelTable(
#            name='alipay',
#            table='ali_pay',
#        ),
    ]
