# Generated by Django 2.0.7 on 2019-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0008_alipay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipay',
            name='ali_pub_key',
            field=models.TextField(blank=True, null=True, verbose_name='证书key'),
        ),
        migrations.AlterField(
            model_name='alipay',
            name='app_pri_key',
            field=models.TextField(blank=True, null=True, verbose_name='证书'),
        ),
        migrations.AlterField(
            model_name='alipay',
            name='app_pub_key',
            field=models.TextField(blank=True, null=True, verbose_name='证书'),
        ),
    ]
