# Generated by Django 2.0.7 on 2019-07-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0009_auto_20190712_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipay',
            name='ali_pub_key',
            field=models.TextField(blank=True, null=True, verbose_name='证书ali_pub_key'),
        ),
        migrations.AlterField(
            model_name='alipay',
            name='app_pri_key',
            field=models.TextField(blank=True, null=True, verbose_name='证书app_pri_key'),
        ),
        migrations.AlterField(
            model_name='alipay',
            name='app_pub_key',
            field=models.TextField(blank=True, null=True, verbose_name='证书app_pub_key'),
        ),
    ]
