# Generated by Django 2.0.7 on 2019-07-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivePlayBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vip', models.IntegerField(default=0, verbose_name='是否仅会员观看')),
                ('title', models.CharField(max_length=20, verbose_name='回放标题')),
                ('speaker', models.CharField(max_length=20, verbose_name='主讲人')),
                ('image_url', models.CharField(max_length=100, null=True, verbose_name='封面图片url')),
                ('details', models.TextField(null=True, verbose_name='详细介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_time', models.IntegerField(default=0, verbose_name='时长')),
                ('state', models.IntegerField(default=0, verbose_name='直播状态')),
                ('media_url', models.CharField(max_length=100, null=True, verbose_name='视频地址')),
            ],
            options={
                'verbose_name': '回放',
                'verbose_name_plural': '回放',
                'db_table': 'live_play_back',
            },
        ),
        migrations.CreateModel(
            name='LiveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='直播标题')),
                ('speaker', models.CharField(max_length=20, verbose_name='主讲人')),
                ('image_url', models.CharField(max_length=100, null=True, verbose_name='封面图片url')),
                ('details', models.TextField(null=True, verbose_name='详细介绍')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('last_time', models.IntegerField(default=0, verbose_name='直播时间')),
                ('state', models.IntegerField(default=0, verbose_name='直播状态')),
            ],
            options={
                'verbose_name': '直播记录',
                'verbose_name_plural': '直播记录',
                'db_table': 'live_record',
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='直播流名称')),
                ('live_type', models.CharField(max_length=20, verbose_name='直播类型')),
                ('pull_stream_url', models.CharField(max_length=100, null=True, verbose_name='推流地址')),
            ],
            options={
                'verbose_name': '直播流',
                'verbose_name_plural': '直播流',
                'db_table': 'live_stream',
            },
        ),
        migrations.CreateModel(
            name='LiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名称')),
            ],
            options={
                'verbose_name': '直播用户',
                'verbose_name_plural': '直播用户',
                'db_table': 'live_user',
            },
        ),
        migrations.AddField(
            model_name='liverecord',
            name='user',
            field=models.ForeignKey(on_delete=None, to='live_app.LiveUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='liveplayback',
            name='user',
            field=models.ForeignKey(on_delete=None, to='live_app.LiveUser', verbose_name='用户'),
        ),
    ]
