# Generated by Django 2.0.7 on 2019-07-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0002_livestream_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverecord',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=None, to='live_app.LiveStream', verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestream',
            name='hdl_stream_url',
            field=models.CharField(max_length=100, null=True, verbose_name='hdl直播地址'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='hls_stream_url',
            field=models.CharField(max_length=100, null=True, verbose_name='hls直播地址'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='rtmp_stream_url',
            field=models.CharField(max_length=100, null=True, verbose_name='rtmp直播地址'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='state',
            field=models.IntegerField(default=1, verbose_name='直播流状态'),
        ),
    ]
