# Generated by Django 2.0.7 on 2019-07-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0004_auto_20190721_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=20, verbose_name='直播流名称')),
                ('live_type', models.CharField(max_length=20, null=True, verbose_name='直播类型')),
                ('stream_url', models.CharField(max_length=100, null=True, verbose_name='直播地址')),
                ('state', models.IntegerField(default=0, verbose_name='直播流状态')),
            ],
            options={
                'verbose_name': '播放流',
                'verbose_name_plural': '播放流',
                'db_table': 'play_stream',
            },
        ),
        migrations.RemoveField(
            model_name='liverecord',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='live_type',
        ),
        migrations.AddField(
            model_name='liverecord',
            name='pull_stream_url',
            field=models.CharField(max_length=100, null=True, verbose_name='推流地址'),
        ),
        migrations.AddField(
            model_name='playstream',
            name='live_record',
            field=models.ForeignKey(on_delete=None, to='live_app.LiveRecord', verbose_name='直播'),
        ),
        migrations.AddField(
            model_name='playstream',
            name='user',
            field=models.ForeignKey(on_delete=None, to='live_app.LiveUser', verbose_name='用户'),
        ),
    ]
