# Generated by Django 2.0.7 on 2019-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0005_auto_20190723_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveplayback',
            name='state',
            field=models.IntegerField(default=2, verbose_name='直播状态'),
        ),
    ]
