# Generated by Django 2.0.7 on 2019-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0006_auto_20190725_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveplayback',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
    ]
