# Generated by Django 2.0.7 on 2019-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0007_liveplayback_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveplayback',
            name='collected',
            field=models.IntegerField(default=0, verbose_name='收藏'),
        ),
    ]
