# Generated by Django 2.0.7 on 2019-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0008_liveplayback_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBackCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(default=0, verbose_name='客户端user_id')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'play_back_collect',
            },
        ),
        migrations.RemoveField(
            model_name='liveplayback',
            name='collected',
        ),
        migrations.AddField(
            model_name='playbackcollect',
            name='play_back',
            field=models.ForeignKey(on_delete=None, to='live_app.LivePlayBack', verbose_name='回放'),
        ),
        migrations.AddField(
            model_name='playbackcollect',
            name='user',
            field=models.ForeignKey(on_delete=None, to='live_app.LiveUser', verbose_name='用户'),
        ),
    ]
