# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pay.proto',
  package='weixin',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tpay.proto\x12\x06weixin\"\x14\n\x04json\x12\x0c\n\x04text\x18\x01 \x01(\t2\x90\x02\n\tWeixinPay\x12*\n\nOrderQuery\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12,\n\x0cUnifiedOrder\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12*\n\nCloseOrder\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12&\n\x06Refund\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12+\n\x0bRefundQuery\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12(\n\x08Micropay\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x32\xd8\x01\n\x06\x41liPay\x12\'\n\x07\x46\x61\x63\x65Pay\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12)\n\tPrecreate\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12&\n\x06\x41ppPay\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12*\n\nOrderQuery\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x12&\n\x06Refund\x12\x0c.weixin.json\x1a\x0c.weixin.json\"\x00\x62\x06proto3')
)




_JSON = _descriptor.Descriptor(
  name='json',
  full_name='weixin.json',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='weixin.json.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=41,
)

DESCRIPTOR.message_types_by_name['json'] = _JSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

json = _reflection.GeneratedProtocolMessageType('json', (_message.Message,), dict(
  DESCRIPTOR = _JSON,
  __module__ = 'pay_pb2'
  # @@protoc_insertion_point(class_scope:weixin.json)
  ))
_sym_db.RegisterMessage(json)



_WEIXINPAY = _descriptor.ServiceDescriptor(
  name='WeixinPay',
  full_name='weixin.WeixinPay',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=44,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='OrderQuery',
    full_name='weixin.WeixinPay.OrderQuery',
    index=0,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UnifiedOrder',
    full_name='weixin.WeixinPay.UnifiedOrder',
    index=1,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseOrder',
    full_name='weixin.WeixinPay.CloseOrder',
    index=2,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Refund',
    full_name='weixin.WeixinPay.Refund',
    index=3,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RefundQuery',
    full_name='weixin.WeixinPay.RefundQuery',
    index=4,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Micropay',
    full_name='weixin.WeixinPay.Micropay',
    index=5,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEIXINPAY)

DESCRIPTOR.services_by_name['WeixinPay'] = _WEIXINPAY


_ALIPAY = _descriptor.ServiceDescriptor(
  name='AliPay',
  full_name='weixin.AliPay',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=319,
  serialized_end=535,
  methods=[
  _descriptor.MethodDescriptor(
    name='FacePay',
    full_name='weixin.AliPay.FacePay',
    index=0,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Precreate',
    full_name='weixin.AliPay.Precreate',
    index=1,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AppPay',
    full_name='weixin.AliPay.AppPay',
    index=2,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OrderQuery',
    full_name='weixin.AliPay.OrderQuery',
    index=3,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Refund',
    full_name='weixin.AliPay.Refund',
    index=4,
    containing_service=None,
    input_type=_JSON,
    output_type=_JSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALIPAY)

DESCRIPTOR.services_by_name['AliPay'] = _ALIPAY

# @@protoc_insertion_point(module_scope)
